apiVersion: apps/v1
kind: Deployment
metadata:
  name: dianaapi-deployment
  labels:
    app: dianaapi-server
spec:
  selector:
    matchLabels:
      app: dianaapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dianaapi-server
    spec:
      containers:
      - name: dianaapi-container
        image: docker.io/dianabeja/7f2e:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dianaapi-server
  name: dianaapi-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: dianaapi-server
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dianaapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dianaapi-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50